### ISSUE TITLE
Confusion about the definition of inside (ON-target dN/dS) and outside the immunopeptidome (OFF-target dN/dS)

### ISSUE THREAD

**Issue by Y-u-q-i** [luisgls/SOPRANO#1]
I had ran SOPRANO following the instructions and it succeeded, and the results it returned was as follows:

From a total of 355 non-silent, 314 missense-only, and 113 silent mutations in input file:
There are 10 non-silent, 9 missense-only, and 0 silent in the (ON) target region
There are 148 non-silent, 129 missense-only, and 46 silent in the (OFF) non-target region

And the SSB_dNdS.txt showed the dN/dS ratios and  so on:
coverage ON_dnds ON_lowci ON_highci ON_muts OFF_dnds OFF_lowci OFF_highci OFF_muts Pval ON_na ON_NA ON_ns ON_NS OFF_na OFF_NA OFF_ns OFF_NS      
ExonicOnly Inf NaN Inf 10 1.1262060785729 0.808959916452559 1.56786566850202 194 1e-04 10 1017410 0 410160 148 13504600 46 4727110       
ExonicIntronic Inf NaN Inf 10 1.1262060785729 0.808959916452559 1.56786566850202 194 1e-04 10 1017410 0 410160 148 13504600 46 4727110 

And I am a little bit confused that if a mutation is not inside the immunopeptidome shouldn't it be outside the immunopeptidome? So in that case why the mutations in the (ON) target region plus the mutations in the (OFF) non-target region don't equal to the total mutations?

Looking forward  to your answers, thanks.

**Comment by luisgls** [comment]
Thanks for this question. The reason for this is that it will calculate OFF dN/dS only on the transcripts that are present on the immunopeptidome file. As the IP file relied on a precomputed set of binding peptides (Top 70 most frequent HLA alleles). There is also the option to exclude driver genes by default (you can turn this off) and see the differences. In your case ON dN/dS is non-computable/Inf as there are no synonymous events in the IP.

**Comment by luisgls** [comment]
We are currently working on expanding the number of transcripts with a precomputed binding value. Also this github will soon be deprecated and replaced by https://github.com/instituteofcancerresearch/SOPRANO/
